version: "3"
x-app: &app
  build:
    context: .
    target: dev
  stdin_open: true
  tty: true
  environment:
    HISTFILE: /usr/src/app/log/.bash_history
  volumes:
    - .:/usr/src/app
    - bundle:/usr/local/bundle
    - node_modules:/app/node_modules

services:
  web:
    <<: *app
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails db:prepare && bin/rails server"
    ports:
      - "3000:3001"

  runner:
    <<: *app
    command: '/bin/bash'
    entrypoint: ''

volumes:
  bundle:
  node_modules:
